export { default as ProductCharacteristic } from './ProductCharacteristic.vue'
export { default as ProductDescription } from './ProductDescription.vue'
export { default as ProductHeader } from './ProductHeader.vue'
export { default as ReleatedItems } from './ReleatedItems.vue'
export { default as SwiperImages } from './SwiperImages.vue'
